export const SET_DATE = 'SET_DATE';
export const SET_TOP1_CONTENT = 'SET_TOP1_CONTENT';

export const GET_CONTENT_SHOW_REQUEST = 'GET_CONTENT_SHOW_REQUEST';
export const GET_CONTENT_SHOW_SUCCESS = 'GET_CONTENT_SHOW_SUCCESS';
export const GET_CONTENT_SHOW_FAILURE = 'GET_CONTENT_SHOW_FAILURE';

export const GET_TOP1_CONTENT_LIST_REQUEST = 'GET_TOP1_CONTENT_LIST_REQUEST';
export const GET_TOP1_CONTENT_LIST_SUCCESS = 'GET_TOP1_CONTENT_LIST_SUCCESS';
export const GET_TOP1_CONTENT_LIST_FAILURE = 'GET_TOP1_CONTENT_LIST_FAILURE';

export const GET_GENRE_SCORE_REQUEST = 'GET_GENRE_SCORE_REQUEST';
export const GET_GENRE_SCORE_SUCCESS = 'GET_GENRE_SCORE_SUCCESS';
export const GET_GENRE_SCORE_FAILURE = 'GET_GENRE_SCORE_FAILURE';
